FROM oven/bun:latest as base

WORKDIR /app
COPY ./tsconfig.json /app/tsconfig.json
COPY ./package.json /app/package.json
COPY ./bun.lockb /app/bun.lockb
COPY . /app

RUN bun install
RUN bun run build

CMD ["bun", "surface.server.bun.ts"]