FROM node:lts-alpine3.19

WORKDIR /app
COPY ./tsconfig.json /app/tsconfig.json
COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json
COPY . .

RUN npm ci
RUN npm run build:node

CMD ["npm", "run", "start:node"]