/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PlayImport } from './routes/play'
import { Route as DocsImport } from './routes/docs'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PlayRoute = PlayImport.update({
  path: '/play',
  getParentRoute: () => rootRoute,
} as any)

const DocsRoute = DocsImport.update({
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/play': {
      preLoaderRoute: typeof PlayImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DocsRoute,
  PlayRoute,
])

/* prettier-ignore-end */
